#! /usr/bin/env bash

echo "Clearing output of documentation notebooks."
jupyter nbconvert --clear-output --inplace "$GIT_WORK_TREE"/docs/source/example.ipynb
git add "$GIT_WORK_TREE"/pylock.toml "$GIT_WORK_TREE"/docs/source/example.ipynb
