name: Build
on:
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build SDist
        run: uv build --sdist --no-progress --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*.tar.gz

  build_wheels:
    name: Build wheels
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # - name: Get CMake
      #   uses: lukka/get-cmake@v3.28.0
       #
      - name: Setup build tools on macOS
        run: brew install automake autoconf libtool
        if: ${{ runner.os == 'macos' }}

      - name: Set deployment target on macOS
        run: echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | cut -d '.' -f 1-2)" >> "$GITHUB_ENV"
        if: ${{ runner.os == 'macos' }}

      - name: Get vcpkg commit ID from manifest
        shell: bash
        run: |
          {
            echo 'vcpkg_json<<EOF'
            cat vcpkg.json
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ fromJson(env.vcpkg_json).builtin-baseline }}
          runVcpkgInstall: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  merge_artifacts:
    name: Merge wheel artifacts
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: wheels
          pattern: wheels-*
          delete-merged: true
