name: Deploy to PyPI
on: 
  push:
    tags-ignore: [*.docs] 
    # only run on tags, and only if they don't end with docs

jobs:
  pypi-publish:
    name: Publish to TestPyPI and PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
      - name: Prepare for upload
        run: |
          mkdir dist
          mv sdist/* dist
          mv wheels/* dist
      # - name: Upload to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/
      #     password: ${{ secrets.TESTPYPI_API_TOKEN }}

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # with:
        #   password: ${{ secrets.PYPI_API_TOKEN }}